// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Materium struct {
	IDMateria   int32          `json:"id_materia"`
	Nombre      string         `json:"nombre"`
	Descripcion sql.NullString `json:"descripcion"`
}

type Opcion struct {
	IDOpcion   int32  `json:"id_opcion"`
	Texto      string `json:"texto"`
	EsCorrecta bool   `json:"es_correcta"`
	IDPregunta int32  `json:"id_pregunta"`
}

type Preguntum struct {
	IDPregunta int32  `json:"id_pregunta"`
	Enunciado  string `json:"enunciado"`
	IDMateria  int32  `json:"id_materia"`
}
