// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const createMateria = `-- name: CreateMateria :one

INSERT INTO materia (nombre, descripcion)
VALUES ($1, $2)
RETURNING id_materia, nombre, descripcion
`

type CreateMateriaParams struct {
	Nombre      string         `json:"nombre"`
	Descripcion sql.NullString `json:"descripcion"`
}

// db/queries/queries.sql
// === Etidad MATERIA ===
func (q *Queries) CreateMateria(ctx context.Context, arg CreateMateriaParams) (Materium, error) {
	row := q.db.QueryRowContext(ctx, createMateria, arg.Nombre, arg.Descripcion)
	var i Materium
	err := row.Scan(&i.IDMateria, &i.Nombre, &i.Descripcion)
	return i, err
}

const createOpcion = `-- name: CreateOpcion :one
INSERT INTO opcion (texto, es_correcta, id_pregunta)
VALUES ($1, $2, $3)
RETURNING id_opcion, texto, es_correcta, id_pregunta
`

type CreateOpcionParams struct {
	Texto      string `json:"texto"`
	EsCorrecta bool   `json:"es_correcta"`
	IDPregunta int32  `json:"id_pregunta"`
}

// === Entidad OPCION ===
func (q *Queries) CreateOpcion(ctx context.Context, arg CreateOpcionParams) (Opcion, error) {
	row := q.db.QueryRowContext(ctx, createOpcion, arg.Texto, arg.EsCorrecta, arg.IDPregunta)
	var i Opcion
	err := row.Scan(
		&i.IDOpcion,
		&i.Texto,
		&i.EsCorrecta,
		&i.IDPregunta,
	)
	return i, err
}

const createPregunta = `-- name: CreatePregunta :one
INSERT INTO pregunta (enunciado, id_materia)
VALUES ($1, $2)
RETURNING id_pregunta, enunciado, id_materia
`

type CreatePreguntaParams struct {
	Enunciado string `json:"enunciado"`
	IDMateria int32  `json:"id_materia"`
}

// === Entidad PREGUNTA ===
func (q *Queries) CreatePregunta(ctx context.Context, arg CreatePreguntaParams) (Preguntum, error) {
	row := q.db.QueryRowContext(ctx, createPregunta, arg.Enunciado, arg.IDMateria)
	var i Preguntum
	err := row.Scan(&i.IDPregunta, &i.Enunciado, &i.IDMateria)
	return i, err
}

const deleteMateria = `-- name: DeleteMateria :exec
DELETE FROM materia
WHERE id_materia = $1
`

func (q *Queries) DeleteMateria(ctx context.Context, idMateria int32) error {
	_, err := q.db.ExecContext(ctx, deleteMateria, idMateria)
	return err
}

const deleteOpcion = `-- name: DeleteOpcion :exec
DELETE FROM opcion
WHERE id_opcion = $1
`

func (q *Queries) DeleteOpcion(ctx context.Context, idOpcion int32) error {
	_, err := q.db.ExecContext(ctx, deleteOpcion, idOpcion)
	return err
}

const deletePregunta = `-- name: DeletePregunta :exec
DELETE FROM pregunta
WHERE id_pregunta = $1
`

func (q *Queries) DeletePregunta(ctx context.Context, idPregunta int32) error {
	_, err := q.db.ExecContext(ctx, deletePregunta, idPregunta)
	return err
}

const getMateria = `-- name: GetMateria :one
SELECT id_materia, nombre, descripcion
FROM materia
WHERE id_materia = $1
`

func (q *Queries) GetMateria(ctx context.Context, idMateria int32) (Materium, error) {
	row := q.db.QueryRowContext(ctx, getMateria, idMateria)
	var i Materium
	err := row.Scan(&i.IDMateria, &i.Nombre, &i.Descripcion)
	return i, err
}

const getOpcion = `-- name: GetOpcion :one
SELECT id_opcion, texto, es_correcta, id_pregunta
FROM opcion
WHERE id_opcion = $1
`

func (q *Queries) GetOpcion(ctx context.Context, idOpcion int32) (Opcion, error) {
	row := q.db.QueryRowContext(ctx, getOpcion, idOpcion)
	var i Opcion
	err := row.Scan(
		&i.IDOpcion,
		&i.Texto,
		&i.EsCorrecta,
		&i.IDPregunta,
	)
	return i, err
}

const getPregunta = `-- name: GetPregunta :one
SELECT id_pregunta, enunciado, id_materia
FROM pregunta
WHERE id_pregunta = $1
`

func (q *Queries) GetPregunta(ctx context.Context, idPregunta int32) (Preguntum, error) {
	row := q.db.QueryRowContext(ctx, getPregunta, idPregunta)
	var i Preguntum
	err := row.Scan(&i.IDPregunta, &i.Enunciado, &i.IDMateria)
	return i, err
}

const listMaterias = `-- name: ListMaterias :many
SELECT id_materia, nombre, descripcion
FROM materia
ORDER BY nombre
`

func (q *Queries) ListMaterias(ctx context.Context) ([]Materium, error) {
	rows, err := q.db.QueryContext(ctx, listMaterias)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Materium
	for rows.Next() {
		var i Materium
		if err := rows.Scan(&i.IDMateria, &i.Nombre, &i.Descripcion); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpcionesByPregunta = `-- name: ListOpcionesByPregunta :many
SELECT id_opcion, texto, es_correcta, id_pregunta
FROM opcion
WHERE id_pregunta = $1
ORDER BY id_opcion
`

func (q *Queries) ListOpcionesByPregunta(ctx context.Context, idPregunta int32) ([]Opcion, error) {
	rows, err := q.db.QueryContext(ctx, listOpcionesByPregunta, idPregunta)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Opcion
	for rows.Next() {
		var i Opcion
		if err := rows.Scan(
			&i.IDOpcion,
			&i.Texto,
			&i.EsCorrecta,
			&i.IDPregunta,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPreguntasByMateria = `-- name: ListPreguntasByMateria :many
SELECT id_pregunta, enunciado, id_materia
FROM pregunta
WHERE id_materia = $1
ORDER BY id_pregunta
`

func (q *Queries) ListPreguntasByMateria(ctx context.Context, idMateria int32) ([]Preguntum, error) {
	rows, err := q.db.QueryContext(ctx, listPreguntasByMateria, idMateria)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Preguntum
	for rows.Next() {
		var i Preguntum
		if err := rows.Scan(&i.IDPregunta, &i.Enunciado, &i.IDMateria); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMateria = `-- name: UpdateMateria :exec
UPDATE materia
SET nombre = $2, descripcion = $3
WHERE id_materia = $1
`

type UpdateMateriaParams struct {
	IDMateria   int32          `json:"id_materia"`
	Nombre      string         `json:"nombre"`
	Descripcion sql.NullString `json:"descripcion"`
}

func (q *Queries) UpdateMateria(ctx context.Context, arg UpdateMateriaParams) error {
	_, err := q.db.ExecContext(ctx, updateMateria, arg.IDMateria, arg.Nombre, arg.Descripcion)
	return err
}

const updateOpcion = `-- name: UpdateOpcion :exec
UPDATE opcion
SET texto = $2, es_correcta = $3
WHERE id_opcion = $1
`

type UpdateOpcionParams struct {
	IDOpcion   int32  `json:"id_opcion"`
	Texto      string `json:"texto"`
	EsCorrecta bool   `json:"es_correcta"`
}

func (q *Queries) UpdateOpcion(ctx context.Context, arg UpdateOpcionParams) error {
	_, err := q.db.ExecContext(ctx, updateOpcion, arg.IDOpcion, arg.Texto, arg.EsCorrecta)
	return err
}

const updatePregunta = `-- name: UpdatePregunta :exec
UPDATE pregunta
SET enunciado = $2, id_materia = $3
WHERE id_pregunta = $1
`

type UpdatePreguntaParams struct {
	IDPregunta int32  `json:"id_pregunta"`
	Enunciado  string `json:"enunciado"`
	IDMateria  int32  `json:"id_materia"`
}

func (q *Queries) UpdatePregunta(ctx context.Context, arg UpdatePreguntaParams) error {
	_, err := q.db.ExecContext(ctx, updatePregunta, arg.IDPregunta, arg.Enunciado, arg.IDMateria)
	return err
}
